<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\URL;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        Model::preventLazyLoading();

        if (app()->environment('production')) {
            URL::forceScheme('https');
        }

        // Ensure lang directory exists and create translation files if not present
        $this->ensureTranslationFiles();
    }

    private function ensureTranslationFiles(): void
    {
        $langPath = resource_path('lang');

        if (!is_dir($langPath)) {
            mkdir($langPath, 0755, true);
        }

        // English translations
        $enFile = $langPath . '/en.json';
        if (!file_exists($enFile)) {
            $this->createEnglishTranslations($enFile);
        }

        // Latvian translations
        $lvFile = $langPath . '/lv.json';
        if (!file_exists($lvFile)) {
            $this->createLatvianTranslations($lvFile);
        }
    }

    private function createEnglishTranslations(string $path): void
    {
        $translations = [
            "app.name" => "LVCareer",
            "app.tagline" => "Find Your Dream Job",
            "nav.home" => "Home",
            "nav.jobs" => "Jobs",
            "nav.internships" => "Internships",
            "nav.contact" => "Contact",
            "nav.login" => "Log In",
            "nav.register" => "Register",
            "nav.admin" => "Admin",
            "nav.dashboard" => "Dashboard",
            "nav.saved" => "Saved",
            "nav.applications" => "Applications",
            "nav.profile" => "My Profile",
            "nav.logout" => "Log Out",
            "nav.adminPanel" => "Admin Panel",
            "home.heading" => "Home",
            "home.badge" => "🇱🇻 Latvia's #1 Career Platform",
            "home.hero.title" => "Find Your Dream",
            "home.hero.titleHighlight" => "Job or Internship",
            "home.hero.subtitle" => "Thousands of opportunities across Latvia — from entry-level to senior roles.",
            "home.search.jobsTab" => "Jobs",
            "home.search.internshipsTab" => "Internships",
            "home.search.jobPlaceholder" => "e.g. PHP Developer, Riga...",
            "home.search.internshipPlaceholder" => "e.g. Marketing, IT internship...",
            "home.search.button" => "Search",
            "home.stats.title" => "Trusted by thousands",
            "home.stats.listings" => "Job Listings",
            "home.stats.companies" => "Companies",
            "home.stats.users" => "Users",
            "jobs.heading" => "Jobs",
            "jobs.postJob" => "Post Job",
            "jobs.noJobs" => "No jobs found",
            "jobs.search" => "Search jobs",
            "jobs.filter" => "Filter",
            "jobs.salary" => "Salary",
            "jobs.type" => "Job Type",
            "jobs.location" => "Location",
            "jobs.experience" => "Experience Level",
            "jobs.applyNow" => "Apply Now",
            "jobs.apply" => "Apply",
            "internships.heading" => "Internships",
            "internships.listingsHeading" => "Internship Listings",
            "internships.postInternship" => "Post Internship",
            "internships.noInternships" => "No internships found",
            "internships.noMatching" => "No internships found matching your criteria.",
            "internships.search" => "Search internships",
            "internships.searchPlaceholder" => "Search by title...",
            "internships.filter" => "Filter",
            "internships.duration" => "Duration",
            "internships.anyDuration" => "Any Duration",
            "internships.month" => "month",
            "internships.months" => "months",
            "internships.locationPlaceholder" => "Location (e.g. Riga)...",
            "internships.clearFilters" => "Clear filters",
            "internships.applyNow" => "Apply Now",
            "internships.apply" => "Apply",
            "contact.heading" => "Contact",
            "contact.subject" => "Subject",
            "contact.message" => "Message",
            "contact.send" => "Send Message",
            "contact.email" => "Email",
            "contact.phone" => "Phone",
            "contact.address" => "Address",
            "contact.support" => "support@lvcareer.lv",
            "contact.tel" => "+371 20 000 000",
            "contact.location" => "Riga, Latvia",
            "auth.login" => "Log In",
            "auth.welcomeBack" => "Welcome back",
            "auth.loginSubtitle" => "Sign in to your LVCareer account",
            "auth.register" => "Register",
            "auth.createAccount" => "Create Account",
            "auth.joinTitle" => "Join LVCareer",
            "auth.joinSubtitle" => "Create your free account in seconds.",
            "auth.roleLabel" => "I am a...",
            "auth.role.jobSeeker" => "Job Seeker",
            "auth.role.student" => "Student",
            "auth.role.employer" => "Employer",
            "auth.email" => "Email",
            "auth.password" => "Password",
            "auth.passwordConfirm" => "Confirm Password",
            "auth.firstName" => "First Name",
            "auth.lastName" => "Last Name",
            "auth.phone" => "Phone",
            "auth.loginButton" => "Log In",
            "auth.registerButton" => "Register",
            "auth.forgotPassword" => "Forgot your password?",
            "auth.noAccount" => "Don't have an account?",
            "auth.haveAccount" => "Already have an account?",
            "auth.rememberMe" => "Remember me",
            "profile.heading" => "My Profile",
            "profile.edit" => "Edit Profile",
            "profile.firstName" => "First Name",
            "profile.lastName" => "Last Name",
            "profile.email" => "Email",
            "profile.phone" => "Phone",
            "profile.save" => "Save Changes",
            "applications.heading" => "My Applications",
            "applications.noApplications" => "No applications yet",
            "applications.status" => "Status",
            "applications.applied" => "Applied",
            "applications.view" => "View",
            "employer.heading" => "Employer Dashboard",
            "employer.applications" => "Applications",
            "employer.listings" => "My Listings",
            "employer.stats" => "Statistics",
            "employer.pending" => "Pending Applications",
            "employer.approved" => "Approved",
            "employer.rejected" => "Rejected",
            "admin.heading" => "Admin Panel",
            "admin.users" => "Users",
            "admin.jobs" => "Jobs",
            "admin.internships" => "Internships",
            "admin.applications" => "Applications",
            "admin.statistics" => "Statistics",
            "admin.manage" => "Manage",
            "admin.delete" => "Delete",
            "admin.edit" => "Edit",
            "admin.view" => "View",
            "footer.description" => "Latvia's platform for jobs, internships and professional opportunities. Connect with top employers.",
            "footer.quickLinks" => "Quick Links",
            "footer.browseJobs" => "Browse Jobs",
            "footer.internships" => "Internships",
            "footer.contact" => "Contact",
            "footer.contactTitle" => "Contact",
            "footer.copyright" => "All rights reserved.",
            "footer.status" => "All systems operational",
            "messages.success" => "Operation successful!",
            "messages.error" => "An error occurred",
            "messages.confirmDelete" => "Are you sure?",
            "buttons.save" => "Save",
            "buttons.cancel" => "Cancel",
            "buttons.delete" => "Delete",
            "buttons.edit" => "Edit",
            "buttons.close" => "Close",
            "buttons.submit" => "Submit",
            "buttons.search" => "Search",
            "buttons.reset" => "Reset",
            "buttons.view" => "View",
            "companies.generic" => "Company",
            "saved.remove" => "Remove from saved",
            "saved.saveInternship" => "Save internship",
            "loading" => "Loading...",
            "noResults" => "No results found",
            "language" => "Language",
            "english" => "English",
            "latvian" => "Latvian"
        ];

        file_put_contents($path, json_encode($translations, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
    }

    private function createLatvianTranslations(string $path): void
    {
        $translations = [
            "app.name" => "LVCareer",
            "app.tagline" => "Atrodiet savu sapņu darbu",
            "nav.home" => "Sākums",
            "nav.jobs" => "Darbi",
            "nav.internships" => "Prakses",
            "nav.contact" => "Kontakti",
            "nav.login" => "Ienākt",
            "nav.register" => "Reģistrēties",
            "nav.admin" => "Administrācija",
            "nav.dashboard" => "Informācijas panelis",
            "nav.saved" => "Saglabātie",
            "nav.applications" => "Pieteikumi",
            "nav.profile" => "Mans profils",
            "nav.logout" => "Izrakstīties",
            "nav.adminPanel" => "Administrācijas panelis",
            "home.heading" => "Sākums",
            "home.badge" => "🇱🇻 Latvijas #1 karjeras platforma",
            "home.hero.title" => "Atrodiet savu sapņu",
            "home.hero.titleHighlight" => "darbu vai praksi",
            "home.hero.subtitle" => "Tūkstošiem iespēju visā Latvijā — no sākuma līmeņa līdz vadošām lomām.",
            "home.search.jobsTab" => "Darbi",
            "home.search.internshipsTab" => "Prakses",
            "home.search.jobPlaceholder" => "piemēram, PHP izstrādātājs, Rīga...",
            "home.search.internshipPlaceholder" => "piemēram, mārketings, IT prakse...",
            "home.search.button" => "Meklēt",
            "home.stats.title" => "Uzticas tūkstošiem",
            "home.stats.listings" => "Darba sludinājumi",
            "home.stats.companies" => "Uzņēmumi",
            "home.stats.users" => "Lietotāji",
            "jobs.heading" => "Darbi",
            "jobs.postJob" => "Publicēt darbu",
            "jobs.noJobs" => "Nav atrasti darbi",
            "jobs.search" => "Meklēt darbus",
            "jobs.filter" => "Filtrs",
            "jobs.salary" => "Alga",
            "jobs.type" => "Darba veids",
            "jobs.location" => "Atrašanās vieta",
            "jobs.experience" => "Pieredzes līmenis",
            "jobs.applyNow" => "Pieteikties tagad",
            "jobs.apply" => "Pieteikties",
            "internships.heading" => "Prakses",
            "internships.listingsHeading" => "Prakses sludinājumi",
            "internships.postInternship" => "Publicēt prakses vietu",
            "internships.noInternships" => "Nav atrastu prakšu",
            "internships.noMatching" => "Nav atrastu prakšu, kas atbilst jūsu kritērijiem.",
            "internships.search" => "Meklēt prakses",
            "internships.searchPlaceholder" => "Meklēt pēc nosaukuma...",
            "internships.filter" => "Filtrs",
            "internships.duration" => "Ilgums",
            "internships.anyDuration" => "Jebkurš ilgums",
            "internships.month" => "mēnesis",
            "internships.months" => "mēneši",
            "internships.locationPlaceholder" => "Atrašanās vieta (piem., Rīga)...",
            "internships.clearFilters" => "Notīrīt filtrus",
            "internships.applyNow" => "Pieteikties tagad",
            "internships.apply" => "Pieteikties",
            "contact.heading" => "Kontakti",
            "contact.subject" => "Temats",
            "contact.message" => "Ziņojums",
            "contact.send" => "Nosūtīt ziņojumu",
            "contact.email" => "E-pasts",
            "contact.phone" => "Telefons",
            "contact.address" => "Adrese",
            "contact.support" => "support@lvcareer.lv",
            "contact.tel" => "+371 20 000 000",
            "contact.location" => "Rīga, Latvija",
            "auth.login" => "Ienākt",
            "auth.welcomeBack" => "Laipni lūdzam atpakaļ",
            "auth.loginSubtitle" => "Ienāciet savā LVCareer kontā",
            "auth.register" => "Reģistrēties",
            "auth.createAccount" => "Izveidot kontu",
            "auth.joinTitle" => "Pievienojieties LVCareer",
            "auth.joinSubtitle" => "Izveidojiet savu bezmaksas kontu dažu sekunžu laikā.",
            "auth.roleLabel" => "Es esmu...",
            "auth.role.jobSeeker" => "Darba meklētājs",
            "auth.role.student" => "Students",
            "auth.role.employer" => "Darba devējs",
            "auth.email" => "E-pasts",
            "auth.password" => "Parole",
            "auth.passwordConfirm" => "Apstipriniet paroli",
            "auth.firstName" => "Vārds",
            "auth.lastName" => "Uzvārds",
            "auth.phone" => "Telefons",
            "auth.loginButton" => "Ienākt",
            "auth.registerButton" => "Reģistrēties",
            "auth.forgotPassword" => "Aizmirsāt paroli?",
            "auth.noAccount" => "Nav konta?",
            "auth.haveAccount" => "Jau ir konts?",
            "auth.rememberMe" => "Atcerēties mani",
            "profile.heading" => "Mans profils",
            "profile.edit" => "Rediģēt profilu",
            "profile.firstName" => "Vārds",
            "profile.lastName" => "Uzvārds",
            "profile.email" => "E-pasts",
            "profile.phone" => "Telefons",
            "profile.save" => "Saglabāt izmaiņas",
            "applications.heading" => "Mani pieteikumi",
            "applications.noApplications" => "Pieteikumi vēl nav iesniegti",
            "applications.status" => "Statuss",
            "applications.applied" => "Pieteikts",
            "applications.view" => "Skatīt",
            "employer.heading" => "Darba devēja informācijas panelis",
            "employer.applications" => "Pieteikumi",
            "employer.listings" => "Mani sludinājumi",
            "employer.stats" => "Statistika",
            "employer.pending" => "Gaidošie pieteikumi",
            "employer.approved" => "Apstiprināti",
            "employer.rejected" => "Noraidīti",
            "admin.heading" => "Administrācijas panelis",
            "admin.users" => "Lietotāji",
            "admin.jobs" => "Darbi",
            "admin.internships" => "Prakses",
            "admin.applications" => "Pieteikumi",
            "admin.statistics" => "Statistika",
            "admin.manage" => "Pārvaldīt",
            "admin.delete" => "Dzēst",
            "admin.edit" => "Rediģēt",
            "admin.view" => "Skatīt",
            "footer.description" => "Latvijas platforma darbam, praksēm un profesionālām iespējām. Savienojieties ar vadošajiem darba devējiem.",
            "footer.quickLinks" => "Ātrās saites",
            "footer.browseJobs" => "Pārlūkot darbus",
            "footer.internships" => "Prakses",
            "footer.contact" => "Kontakti",
            "footer.contactTitle" => "Kontakti",
            "footer.copyright" => "Visas tiesības aizsargātas.",
            "footer.status" => "Visas sistēmas darbojas",
            "messages.success" => "Darbība veiksmīga!",
            "messages.error" => "Radās kļūda",
            "messages.confirmDelete" => "Vai tiešām vēlaties dzēst?",
            "buttons.save" => "Saglabāt",
            "buttons.cancel" => "Atcelt",
            "buttons.delete" => "Dzēst",
            "buttons.edit" => "Rediģēt",
            "buttons.close" => "Aizvērt",
            "buttons.submit" => "Nosūtīt",
            "buttons.search" => "Meklēt",
            "buttons.reset" => "Atiestatīt",
            "buttons.view" => "Skatīt",
            "companies.generic" => "Uzņēmums",
            "saved.remove" => "Noņemt no saglabātajiem",
            "saved.saveInternship" => "Saglabāt praksi",
            "loading" => "Ielādē...",
            "noResults" => "Rezultāti nav atrasti",
            "language" => "Valoda",
            "english" => "Angļu",
            "latvian" => "Latviešu"
        ];

        file_put_contents($path, json_encode($translations, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
    }
}
